#!/bin/sh
# C:\Users\asus\scoop\apps\composer\current\composer.ps1
if command -v pwsh.exe > /dev/null 2>&1; then
    pwsh.exe -noprofile -ex unrestricted -file "C:\Users\asus\scoop\apps\composer\current\composer.ps1"  "$@"
else
    powershell.exe -noprofile -ex unrestricted -file "C:\Users\asus\scoop\apps\composer\current\composer.ps1"  "$@"
fi