<?php return array(
    'root' => array(
        'name' => 'doctrine/orm',
        'pretty_version' => 'dev-master',
        'version' => 'dev-master',
        'reference' => '2cd33f31ac0dc6648aea0e4e3c0a7c09e9b69b8b',
        'type' => 'library',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => true,
    ),
    'versions' => array(
        'doctrine/orm' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => '2cd33f31ac0dc6648aea0e4e3c0a7c09e9b69b8b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php80' => array(
            'pretty_version' => 'v1.27.0',
            'version' => '1.27.0.0',
            'reference' => '7a6ff3f1959bb01aefccb463a0f2cd3d3d2fd936',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php80',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/runtime' => array(
            'pretty_version' => 'v5.4.25',
            'version' => '5.4.25.0',
            'reference' => '03e9c5d74464213a47a2ad8dc8eb249613701d6f',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/../symfony/runtime',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
